!include ../openmc.i

# Locally generated by this case directory's own mesh-only pass (see
# ../multiphysics_amr.sh), so this stays a bare filename regardless of which
# case directory this file is symlinked into as openmc.i.
[Mesh]
  [file_mesh]
    type = FileMeshGenerator
    file = mesh_neutronics_in.e
  []
  length_unit = 'm'
[]

[MultiApps]
  [solid]
    input_files := ../solid.i
  []
  [sub_channel]
    input_files := ../sub_channel.i
  []
[]
